[package]
name = "zoo-scanner"
version = "0.1.0"
authors = ["jinnzoo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.20.3"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
curl = "0.4.8"
